name: Core Build

on:
  pull_request:
    branches:
      - dev
      - prod

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Use Node 18
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'

      - run: yarn
        name: Install Dependencies

      - name: Run Lint
        run: yarn lint

      - name: Build Project
        run: yarn build
