name: Release Package

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Use Node 18
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'

      - run: yarn
        name: Install Dependencies

      - name: Build Package
        run: yarn build

      - name: Create new Release
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
